kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: elk-kafka
  name: pod-list
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
