apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: elk-kafka
  labels:
    k8s-app: fluentd-logging
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.9.2-debian-kafka-1.0
        env:
          - name:  FLUENT_KAFKA_BROKERS
            value: "cluster-1-kafka-brokers:9092"
          - name:  FLUENT_KAFKA_DEFAULT_TOPIC
            value: "your-logs-topic"
          - name: FLUENT_KAFKA_REQUIRED_ACKS
            value: "1"
          - name: FLUENT_KAFKA_COMPRESSION_CODEC
            value: "gzip"
          - name: FLUENT_KAFKA_MAX_SEND_LIMIT_BYTES
            value: "1000000"
          # Option to configure elasticsearch plugin with self signed certs
          # ================================================================
          # - name: FLUENT_ELASTICSEARCH_SSL_VERIFY
          #   value: "true"
          # Option to configure elasticsearch plugin with tls
          # ================================================================
          # - name: FLUENT_ELASTICSEARCH_SSL_VERSION
          #   value: "TLSv1_2"
          # X-Pack Authentication
          # =====================
          # - name: FLUENT_ELASTICSEARCH_USER
          #   value: "elastic"
          # - name: FLUENT_ELASTICSEARCH_PASSWORD
          #   value: "changeme"
          # Logz.io Authentication
          # ======================
          # - name: LOGZIO_TOKEN
          #   value: "ThisIsASuperLongToken"
          # - name: LOGZIO_LOGTYPE
          #   value: "kubernetes"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
