kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-rolebinding
  namespace: elk-kafka
subjects:
- kind: ServiceAccount
  name: default
  namespace: elk-kafka
roleRef:
  kind: ClusterRole
  name: pod-list
  apiGroup: rbac.authorization.k8s.io
