apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: cluster-1
spec:
  kafka:
    version: 2.4.0
    replicas: 3
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: '2.4'
      log.retention.minutes: 2
      log.segment.bytes: 741824
    storage:
      type: persistent-claim
      size: 6Gi
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 1Gi
  entityOperator:
    topicOperator: {}
    userOperator: {}
